Lesson5/Controllers/Exercise03Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lesson5.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lesson5.Controllers
{
    public class Exercise03Controller : Controller
    {
        public IActionResult Index()
        {
            BreakfastOrder breakfastOrder = new BreakfastOrder();
            //when using curly brackets here, you're not passing into the constructor but setting the properties directly, instead of 
            //new class()
            //class.prop1 = "somevalue"
            breakfastOrder.addBreakfastFood(new BreakfastFood { BreakfastFoodId = 1, Name = "Cornflakes", Price = 36, Selected = false });
            breakfastOrder.addBreakfastFood(new BreakfastFood { BreakfastFoodId = 2, Name = "Eggs", Price = 16, Selected = false });
            breakfastOrder.addBreakfastFood(new BreakfastFood { BreakfastFoodId = 3, Name = "Toast", Price = 10, Selected = false });
            breakfastOrder.addBreakfastFood(new BreakfastFood { BreakfastFoodId = 4, Name = "Juice", Price = 4, Selected = false });
            breakfastOrder.addBreakfastFood(new BreakfastFood { BreakfastFoodId = 5, Name = "Coffee", Price = 3, Selected = false });
            breakfastOrder.addBreakfastFood(new BreakfastFood { BreakfastFoodId = 6, Name = "Tea", Price = 2, Selected = false });
            //return the view with model as parameter, creates strongly typed view:
            return View(breakfastOrder);
        }




        [HttpPost]
        public IActionResult Index(BreakfastOrder breakfastOrder)
        {
            if (ModelState.IsValid)
            {
                return View("Receipt", breakfastOrder);
            }
            return View(breakfastOrder);


        }
    }
}

Lesson5/Views/Exercise03/Index.cshtml
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers" 
@using Lesson5.Models;
@model BreakfastOrder

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Breakfast order</title>
    <style>
        .summary-validation-error {
            color: #f00;
        }

        .input-validation-error {
            border: 2px solid #f00;
            background-color: #fee;
        }

        .field-validation-error {
            color: #f00;
        }
    </style>
</head>
<body>
    <h1>Breakfast order</h1>
    <form method="post" asp-controller="Exercise03" asp-action="Index">
        <label asp-for="FullName"></label><input asp-for="FullName" /><span asp-validation-for="FullName" class="text-danger"></span><br />
        <label asp-for="RoomNumber"> </label><input type="number" asp-for="RoomNumber" />
        <span asp-validation-for="RoomNumber" class="text-danger"></span>
        <p>
            What would you like to eat for breakfast?<br /><br />

            @for (int i = 0; i < Model.BreakfastFoods.Count(); i++)
            {
                <input asp-for="@Model.BreakfastFoods[i].Selected" type="checkbox" />
                @Model.BreakfastFoods[i].Name <br />
                <input asp-for="@Model.BreakfastFoods[i].BreakfastFoodId" type="hidden" />
                <input asp-for="@Model.BreakfastFoods[i].Name" type="hidden" />
                <input asp-for="@Model.BreakfastFoods[i].Price" type="hidden" />
            }
            @*when posting the form to the controller, i'll recieve the result as a collection of BreakfastFood objects*@
        </p>
        <span asp-validation-for="BreakfastFoods"></span><br />
        <label asp-for="Delivery">When:  </label><input asp-for="Delivery" /><span asp-validation-for="Delivery"></span>
        <p> <input type="submit" value="Order" /> </p>
    </form>

    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js">
    </script>
</body>
</html>

Lesson5/Views/Exercise03/Receipt.cshtml
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@using Lesson5.Models;
@model BreakfastOrder
@using System.Globalization;

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Breakfast order</title>
</head>
<body>
    <h1>Your breakfast order</h1>
    <p>Hello @Model.FullName !</p>
    <p>You ordered:</p>
    <ul>
        @for (int i = 0; i < Model.BreakfastFoods.Count(); i++)
        {
            @if (Model.BreakfastFoods[i].Selected == true)

            {
                <li>@Model.BreakfastFoods[i].Name - @Model.BreakfastFoods[i].Price.ToString("C2",
                  CultureInfo.CreateSpecificCulture("da-DK"))</li>
}

        }
    </ul>
    <p>Total price: @Model.TotalPrice.ToString("C2",
                  CultureInfo.CreateSpecificCulture("da-DK"))</p>

    <p>Your order will be prepared and delivered to room number @Model.RoomNumber, on @Model.Delivery.ToString("R")</p>

</body>
</html>