Lesson5/Controllers/RemoteController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lesson5.Models;
using Lesson5.Infrastructure;

namespace Lesson5.Controllers
{
    public class RemoteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(User newUser)
        {
            if (ModelState.IsValid)
            {
                return View("NewUserCreated", newUser);
            }
            return View(newUser);


        }

        public JsonResult UniqueUserName(string Username)
        {
            if(Users.UsernameIsUnique(Username))
            {
                return Json(true);
            }
            else
            {
                return Json("This username already exists");
            }
           
        }
    }
}

Lesson5/Views/Remote/Index.cshtml
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@using Lesson5.Models;
@model User;

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Check Existing User</title>
    <style>
        .summary-validation-error {
            color: #f00;
        }

        .input-validation-error {
            border: 2px solid #f00;
            background-color: #fee;
        }

        .field-validation-error {
            color: #f00;
        }
    </style>
</head>
<body>
    <h1>Check Existing User</h1>
    <form method="post" asp-controller="Remote" asp-action="Index">
        <label asp-for="Username"></label><input asp-for="Username" /><span asp-validation-for="Username" class="text-danger"></span><br />
    
        <p> <input type="submit" value="Create User" /> </p>
    </form>


    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js">
    </script>
</body>
</html>

Lesson5/Views/Remote/NewUserCreated.cshtml
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@using Lesson5.Models;
@model User;

    <div>@Model.Username is now created</div>

Lesson5/Views/Remote/TestView.cshtml
@model Lesson5.Models.User

@{
    ViewData["Title"] = "TestView";
}

<h1>TestView</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="TestView">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}